import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { appConfig } from '../../../packages/shared/src/app-config.ts';
import { BUTTON_KEYS, ENTRY_KEYS, QUESTION_TYPE_KEYS, STATS_KEYS } from '../../../packages/shared/src/telemetry/registry.ts';
import { statsDocumentId } from '../../../packages/shared/src/telemetry/queue.ts';
import { anonymousDeleteRequest, anonymousSignUpRequest, encodeStatsFields, interpretCreateStatus, statsCollection, statsCreateRequest } from '../../../packages/shared/src/telemetry/transport.ts';
import { TELEMETRY_EXEMPT_FILES, payload, telemetryExemptSources } from './fixtures.ts';
const sort = (a: readonly string[]) => [...a].sort();
const enc = () => encodeStatsFields(payload());
const fields = (v: unknown) => (v as { mapValue: { fields: Record<string, unknown> } }).mapValue.fields;
test('T-1 statsCollection(true) は official を返す', () => assert.equal(statsCollection(true), 'stats_days_official'));
test('T-2 statsCollection(false) は test を返す', () => assert.equal(statsCollection(false), 'stats_days_test'));
test('T-3 encodeStatsFields のキー集合は STATS_KEYS と一致する', () => assert.deepEqual(sort(Object.keys(enc())), sort(STATS_KEYS)));
test('T-4 buttonCounts のキー集合は BUTTON_KEYS と一致する', () => assert.deepEqual(sort(Object.keys(fields(enc().buttonCounts))), sort(BUTTON_KEYS)));
test('T-5 entryCounts のキー集合は ENTRY_KEYS と一致する', () => assert.deepEqual(sort(Object.keys(fields(enc().entryCounts))), sort(ENTRY_KEYS)));
test('T-6 questionTypeCounts のキー集合は QUESTION_TYPE_KEYS と一致する', () => assert.deepEqual(sort(Object.keys(fields(enc().questionTypeCounts))), sort(QUESTION_TYPE_KEYS)));
test('T-7 整数は文字列の integerValue になる', () => { for (const key of ['pageViews', 'attemptCount', 'dataVersion', 'masteryRulesVersion']) assert.equal(typeof (enc()[key] as { integerValue: unknown }).integerValue, 'string'); });
test('T-8 習熟度は number の doubleValue になる', () => { for (const key of ['masteryAvg', 'masteryMax']) { const value = enc()[key] as { doubleValue: unknown; integerValue?: unknown }; assert.equal(typeof value.doubleValue, 'number'); assert.equal(value.integerValue, undefined); } });
test('T-9 masteryDistribution は文字列 integerValue の配列になる', () => { const values = (enc().masteryDistribution as { arrayValue: { values: Array<{ integerValue: unknown }> } }).arrayValue.values; assert.equal(values.length, 5); values.forEach((v) => assert.equal(typeof v.integerValue, 'string')); });
test('T-10 文字列、時刻、真偽値を REST Value にする', () => { const p = payload(); const e = encodeStatsFields(p); for (const key of ['clientNumber', 'localDate', 'product', 'grade', 'appVersion']) assert.equal(typeof (e[key] as { stringValue: unknown }).stringValue, 'string'); assert.equal((e.expiresAt as { timestampValue: unknown }).timestampValue, `${p.expiresAt}T00:00:00.000Z`); assert.equal((e.isOfficial as { booleanValue: unknown }).booleanValue, p.isOfficial); });
test('T-11 作成 URL は payload の official と文書 ID を使う', () => { for (const isOfficial of [true, false]) { const p = { ...payload(), isOfficial }; const url = statsCreateRequest(appConfig.firebase, { payload: p, idToken: 'token', appCheckToken: null }).url; assert.ok(url.includes('/projects/' + appConfig.firebase.projectId + '/databases/(default)/'), 'T-11: projectId が URL に無い'); assert.match(url, new RegExp(`/documents/${statsCollection(isOfficial)}\\?documentId=${statsDocumentId(p)}$`)); } });
test('T-12 App Check ヘッダはトークンがあるときだけ付く', () => { const o = { payload: payload(), idToken: 'token' }; assert.equal(statsCreateRequest(appConfig.firebase, { ...o, appCheckToken: 'check' }).headers['X-Firebase-AppCheck'], 'check'); assert.equal(statsCreateRequest(appConfig.firebase, { ...o, appCheckToken: null }).headers['X-Firebase-AppCheck'], undefined); });
test('T-13 create はトークンを Authorization のみに置く', () => { const r = statsCreateRequest(appConfig.firebase, { payload: payload(), idToken: 'token', appCheckToken: null }); assert.equal(r.headers.Authorization, 'Bearer token'); assert.equal(r.body.includes('token'), false); const del = anonymousDeleteRequest(appConfig.firebase, 'token'); assert.equal(del.body.includes('token'), true); assert.ok(del.url.includes(`key=${appConfig.firebase.apiKey}`), `T-13: delete の URL に apiKey が無い`); });
test('T-14 create の成功と再試行の状態を解釈する', () => { for (const [s, v] of [[200, 'sent'], [409, 'sent'], [400, 'retry'], [401, 'retry'], [403, 'retry'], [429, 'retry'], [500, 'retry'], [0, 'retry']] as const) assert.equal(interpretCreateStatus(s), v); });
test('T-15 anonymous sign-up は API key を使い Authorization を持たない', () => { const r = anonymousSignUpRequest(appConfig.firebase); assert.match(r.url, /accounts:signUp/); assert.ok(r.url.includes(`key=${appConfig.firebase.apiKey}`), `T-15: signUp の URL に apiKey が無い`); assert.equal(r.headers.Authorization, undefined); });
test('T-16 免除ファイルに永続化、時刻、DOM、個別履歴、console が無い', () => { const sources = telemetryExemptSources(); assert.ok(sources.length); assert.deepEqual(sources.map((s) => s.file), [...TELEMETRY_EXEMPT_FILES]); for (const s of sources) { assert.ok(s.text.length); for (const word of ['localStorage', 'sessionStorage', 'indexedDB', 'document.cookie', 'Date.now', 'toISOString', 'getTimezoneOffset', 'textContent', 'innerHTML', 'getAttribute', 'poemId', 'questionId', 'sessionId', 'eventId', 'console']) assert.equal(s.text.includes(word), false); } });
test('T-17 transport.ts は送信 API を呼ばない', () => { const text = readFileSync(join(process.cwd(), 'packages/shared/src/telemetry/transport.ts'), 'utf8'); for (const word of ['fetch(', 'XMLHttpRequest', 'sendBeacon']) assert.equal(text.includes(word), false); });
test('T-18 dependencies は preact だけである', () => assert.deepEqual(Object.keys((JSON.parse(readFileSync('package.json', 'utf8')) as { dependencies: object }).dependencies), ['preact']));
