import { appConfig } from '../app-config.ts';
import { statsDocumentId } from './queue.ts';
import { BUTTON_KEYS, ENTRY_KEYS, QUESTION_TYPE_KEYS } from './registry.ts';
import type { StatsPayload } from './registry.ts';
export type HttpRequestSpec = { url: string; method: 'POST'; headers: Record<string, string>; body: string };
export type SendOutcome = 'sent' | 'retry';
export type FirebaseWebConfig = typeof appConfig.firebase;
const integerValue = (value: number): { integerValue: string } => ({ integerValue: String(value) });
function counts<Key extends string>(map: Record<Key, number>, keys: readonly Key[]): Record<string, unknown> { return Object.fromEntries(keys.map((key) => [key, integerValue(map[key])])); }
export function statsCollection(isOfficial: boolean): string { return isOfficial ? 'stats_days_official' : 'stats_days_test'; }
export function encodeStatsFields(payload: StatsPayload): Record<string, unknown> { return { clientNumber: { stringValue: payload.clientNumber }, localDate: { stringValue: payload.localDate }, product: { stringValue: payload.product }, grade: { stringValue: payload.grade }, pageViews: integerValue(payload.pageViews), buttonCounts: { mapValue: { fields: counts(payload.buttonCounts, BUTTON_KEYS) } }, entryCounts: { mapValue: { fields: counts(payload.entryCounts, ENTRY_KEYS) } }, questionTypeCounts: { mapValue: { fields: counts(payload.questionTypeCounts, QUESTION_TYPE_KEYS) } }, attemptCount: integerValue(payload.attemptCount), masteryAvg: { doubleValue: payload.masteryAvg }, masteryMax: { doubleValue: payload.masteryMax }, masteryDistribution: { arrayValue: { values: payload.masteryDistribution.map(integerValue) } }, isOfficial: { booleanValue: payload.isOfficial }, appVersion: { stringValue: payload.appVersion }, dataVersion: integerValue(payload.dataVersion), masteryRulesVersion: integerValue(payload.masteryRulesVersion), expiresAt: { timestampValue: `${payload.expiresAt}T00:00:00.000Z` } }; }
export function anonymousSignUpRequest(config: FirebaseWebConfig): HttpRequestSpec { return { url: `https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${config.apiKey}`, method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ returnSecureToken: true }) }; }
export function anonymousDeleteRequest(config: FirebaseWebConfig, idToken: string): HttpRequestSpec { return { url: `https://identitytoolkit.googleapis.com/v1/accounts:delete?key=${config.apiKey}`, method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` }, body: JSON.stringify({ idToken }) }; }
export function statsCreateRequest(config: FirebaseWebConfig, options: { payload: StatsPayload; idToken: string; appCheckToken: string | null }): HttpRequestSpec { const { payload, idToken, appCheckToken } = options; const headers: Record<string, string> = { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` }; if (appCheckToken !== null) headers['X-Firebase-AppCheck'] = appCheckToken; return { url: `https://firestore.googleapis.com/v1/projects/${config.projectId}/databases/(default)/documents/${statsCollection(payload.isOfficial)}?documentId=${statsDocumentId(payload)}`, method: 'POST', headers, body: JSON.stringify({ fields: encodeStatsFields(payload) }) }; }
export function interpretCreateStatus(status: number): SendOutcome { return status === 200 || status === 409 ? 'sent' : 'retry'; }
